FROM node:22-alpine AS base

FROM base AS deps
WORKDIR /app
COPY ["package.json", "package-lock.json", "./"]
ENV NODE_ENV=production
RUN npm ci && npm cache clean --force

FROM base AS dev
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY ./ ./

CMD ["npm", "run", "start:docker"]
