name: hls24q3-part2
services:
  hls-database:
    image: postgres:alpine
    ports:
      - 5432:${DB_CONTAINER_PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    container_name: ${DB_CONTAINER_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data
      - db_logs:/logs
    restart: always

volumes:
  db_data:
  db_logs: